version: "3.3"

networks:
  naturally:
    driver: bridge

services:
  db:
    container_name: naturallydb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    image: mysql:5.7
    networks:
      - naturally
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./storage/database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: naturallymyadmin
    networks:
      - naturally
    ports:
      - 8181:80

  nginx-server:
    container_name: naturallyserver
    build: ./docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - php-fpm
    networks:
      - naturally

  php-fpm:
    container_name: naturallyweb
    restart: always
    build: ./docker/php-fpm
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db
    networks:
      - naturally