version: "3.6"

networks:
  naturally:
    driver: bridge

services:
  db:
    container_name: naturally-server-db
    environment:
      MYSQL_ROOT_PASSWORD: "e2CS#TjE=Zs3AA"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    image: mysql:5.7
    networks:
      - naturally
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./storage/database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: naturally-server-phpmyadmin
    networks:
      - naturally
    ports:
      - 8181:80

  nginx-server:
    container_name: naturally-server-nginx
    build: ./docker/nginx
    restart: always
    ports:
      - "8080:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - php-fpm
    networks:
      - naturally

  php-fpm:
    container_name: naturally-server-php_fpm
    restart: always
    build: ./docker/php-fpm
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db
    networks:
      - naturally